version: '3.8'

services:
  mariadb_sangil:
    image: mariadb:10.11
    container_name: mariadb_sangil_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sistema_taxis_sangil
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: devpassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:



version: '3'
services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "5055:5055"
    volumes:
      - ./logs:/opt/traccar/logs
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml